In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Function to convert radians to degrees
def rad_to_deg(rad):
    return rad * 180 / np.pi

# Load the CSV files
iso_df = pd.read_csv('results/bootstrap_results_isotropic.csv')
ideal_df = pd.read_csv('results/bootstrap_results_ideal.csv')

# Let's focus on the alpha parameters in the isotropic results and theta0 in ideal results
# First, identify all the alpha columns in the isotropic dataframe
alpha_cols = [col for col in iso_df['Parameter'] if 'alpha' in col]

# Create a new dataframe to store the results
results = []

# Process isotropic data
for param in iso_df['Parameter']:
    row = iso_df[iso_df['Parameter'] == param].iloc[0]
    
    # Convert alpha values to degrees if they're alpha parameters
    if 'alpha' in param:
        mean = rad_to_deg(row['Mean'])
        median = rad_to_deg(row['Median'])
        std = rad_to_deg(row['Std'])
        ci_68_lower = rad_to_deg(row['68.0%_lower'])
        ci_68_upper = rad_to_deg(row['68.0%_upper'])
        ci_90_lower = rad_to_deg(row['90.0%_lower'])
        ci_90_upper = rad_to_deg(row['90.0%_upper'])
        ci_95_lower = rad_to_deg(row['95.0%_lower'])
        ci_95_upper = rad_to_deg(row['95.0%_upper'])
        ci_99_lower = rad_to_deg(row['99.0%_lower'])
        ci_99_upper = rad_to_deg(row['99.0%_upper'])
    else:
        mean = row['Mean']
        median = row['Median']
        std = row['Std']
        ci_68_lower = row['68.0%_lower']
        ci_68_upper = row['68.0%_upper']
        ci_90_lower = row['90.0%_lower']
        ci_90_upper = row['90.0%_upper']
        ci_95_lower = row['95.0%_lower']
        ci_95_upper = row['95.0%_upper']
        ci_99_lower = row['99.0%_lower']
        ci_99_upper = row['99.0%_upper']
    
    # Calculate differences
    diff_median_68_lower = median - ci_68_lower
    diff_median_68_upper = ci_68_upper - median
    diff_median_90_lower = median - ci_90_lower
    diff_median_90_upper = ci_90_upper - median
    diff_median_95_lower = median - ci_95_lower
    diff_median_95_upper = ci_95_upper - median
    diff_median_99_lower = median - ci_99_lower
    diff_median_99_upper = ci_99_upper - median
    diff_mean_minus_std = mean - std
    diff_mean_plus_std = mean + std
    
    results.append({
        'Parameter': param,
        'Mean': mean,
        'Median': median,
        'Std': std,
        'Median-68%_lower': diff_median_68_lower,
        '68%_upper-Median': diff_median_68_upper,
        'Median-90%_lower': diff_median_90_lower,
        '90%_upper-Median': diff_median_90_upper,
        'Median-95%_lower': diff_median_95_lower,
        '95%_upper-Median': diff_median_95_upper,
        'Median-99%_lower': diff_median_99_lower,
        '99%_upper-Median': diff_median_99_upper,
        'Mean-Std': diff_mean_minus_std,
        'Mean+Std': diff_mean_plus_std
    })

results_df = pd.DataFrame(results)
results_df.to_csv('results/bs_final_isotropic.csv', index=False)
results_df

,Parameter,Mean,Median,Std,Median-68%_lower,68%_upper-Median,Median-90%_lower,90%_upper-Median,Median-95%_lower,95%_upper-Median,Median-99%_lower,99%_upper-Median,Mean-Std,Mean+Std
0,N,357.399115,357.395255,0.010221,0.000218,0.007727,0.000327,0.018683,0.000938,0.023156,0.002577,0.060135,357.388894,357.409336
1,r,77.920925,77.923109,0.007714,0.007853,0.002824,0.019122,0.008052,0.022992,0.008926,0.025941,0.009787,77.913211,77.928639
2,sigma,0.086602,0.086074,0.004711,0.004434,0.005321,0.006690,0.009166,0.007594,0.009981,0.010052,0.011046,0.081892,0.091313
3,x0_0,80.095453,80.096901,0.003373,0.003384,0.000251,0.006639,0.000331,0.007216,0.000333,0.018164,0.000348,80.092080,80.098826
4,y0_0,136.371224,136.372207,0.002290,0.002297,0.000171,0.004507,0.000224,0.004898,0.000225,0.012328,0.000236,136.368934,136.373513
5,alpha_0,214.165265,214.165495,0.001519,0.001974,0.000855,0.002604,0.001962,0.003361,0.002696,0.003822,0.004349,214.163746,214.166783
6,x0_1,80.102349,80.107755,0.009122,0.015245,0.001704,0.023807,0.001820,0.025195,0.002024,0.032121,0.002235,80.093227,80.111471
7,y0_1,136.467116,136.472534,0.008982,0.016052,0.001318,0.022087,0.001485,0.028197,0.001847,0.031323,0.003924,136.458135,136.476098
8,alpha_1,214.352140,214.351703,0.021990,0.021200,0.023768,0.036245,0.037105,0.043970,0.042620,0.051629,0.051400,214.330150,214.374131
9,x0_2,80.234498,80.236077,0.006074,0.003594,0.000327,0.014652,0.005240,0.015355,0.006129,0.027474,0.013311,80.228424,80.240572
10,y0_2,136.203900,136.206428,0.009989,0.006482,0.000593,0.027359,0.008738,0.028111,0.010744,0.037530,0.026341,136.193911,136.213888
11,alpha_2,214.453419,214.451490,0.020608,0.020091,0.022055,0.027524,0.038410,0.031729,0.046540,0.042475,0.049880,214.432811,214.474027
12,x0_3,79.858058,79.853223,0.009248,0.000539,0.011299,0.000607,0.021006,0.000613,0.024046,0.001820,0.049340,79.848810,79.867306
13,y0_3,136.291567,136.290503,0.010351,0.001204,0.010930,0.021512,0.017218,0.026297,0.020010,0.030581,0.023397,136.281216,136.301918
14,alpha_3,214.803957,214.804406,0.013186,0.013703,0.011270,0.019688,0.019738,0.028480,0.023911,0.031697,0.027297,214.790771,214.817144
15,x0_4,80.506608,80.505443,0.002651,0.000237,0.002872,0.000309,0.005013,0.000310,0.005848,0.000324,0.014245,80.503957,80.509259
16,y0_4,136.464175,136.468919,0.010798,0.011699,0.000966,0.020415,0.001258,0.023816,0.001264,0.058017,0.001322,136.453377,136.474972
17,alpha_4,214.290643,214.290013,0.002190,0.000875,0.001247,0.001129,0.004770,0.001450,0.006872,0.001619,0.010666,214.288454,214.292833
18,x0_5,80.510317,80.508553,0.003642,0.000254,0.003849,0.000328,0.007613,0.000331,0.007750,0.000352,0.019682,80.506674,80.513959
19,y0_5,136.481566,136.487539,0.012255,0.013516,0.000960,0.025877,0.001197,0.026153,0.001203,0.065354,0.001272,136.469311,136.493822
20,alpha_5,214.316005,214.313096,0.034083,0.039419,0.042920,0.046826,0.047219,0.051883,0.075132,0.055914,0.084970,214.281923,214.350088
21,x0_6,80.616321,80.615257,0.002388,0.000228,0.002675,0.000302,0.004573,0.000303,0.006138,0.000320,0.012616,80.613933,80.618709
22,y0_6,136.185850,136.188974,0.006997,0.007932,0.000708,0.013633,0.000867,0.017924,0.000868,0.036820,0.000908,136.178854,136.192847
23,alpha_6,214.673600,214.675171,0.041457,0.059289,0.058441,0.060073,0.060250,0.060403,0.061103,0.061273,0.062149,214.632143,214.715058
24,x0_7,80.765379,80.769567,0.008642,0.011191,0.000364,0.024144,0.002628,0.029235,0.003035,0.032788,0.006283,80.756736,80.774021
25,y0_7,136.059771,136.047611,0.022724,0.001038,0.031573,0.002638,0.064686,0.005141,0.077676,0.006125,0.086532,136.037047,136.082495
26,alpha_7,214.453919,214.458223,0.032383,0.040212,0.025304,0.061749,0.046726,0.066523,0.050585,0.075495,0.069552,214.421536,214.486302

In [2]:
results = []
# Process ideal data
for param in ideal_df['Parameter']:
    row = ideal_df[ideal_df['Parameter'] == param].iloc[0]
    
    # Convert theta0 values to degrees if it's theta0
    if param == 'theta0':
        mean = rad_to_deg(row['Mean'])
        median = rad_to_deg(row['Median'])
        std = rad_to_deg(row['Std'])
        ci_68_lower = rad_to_deg(row['68.0%_lower'])
        ci_68_upper = rad_to_deg(row['68.0%_upper'])
        ci_90_lower = rad_to_deg(row['90.0%_lower'])
        ci_90_upper = rad_to_deg(row['90.0%_upper'])
        ci_95_lower = rad_to_deg(row['95.0%_lower'])
        ci_95_upper = rad_to_deg(row['95.0%_upper'])
        ci_99_lower = rad_to_deg(row['99.0%_lower'])
        ci_99_upper = rad_to_deg(row['99.0%_upper'])
    else:
        mean = row['Mean']
        median = row['Median']
        std = row['Std']
        ci_68_lower = row['68.0%_lower']
        ci_68_upper = row['68.0%_upper']
        ci_90_lower = row['90.0%_lower']
        ci_90_upper = row['90.0%_upper']
        ci_95_lower = row['95.0%_lower']
        ci_95_upper = row['95.0%_upper']
        ci_99_lower = row['99.0%_lower']
        ci_99_upper = row['99.0%_upper']
    
    # Calculate differences
    diff_median_68_lower = median - ci_68_lower
    diff_median_68_upper = ci_68_upper - median
    diff_median_90_lower = median - ci_90_lower
    diff_median_90_upper = ci_90_upper - median
    diff_median_95_lower = median - ci_95_lower
    diff_median_95_upper = ci_95_upper - median
    diff_median_99_lower = median - ci_99_lower
    diff_median_99_upper = ci_99_upper - median
    diff_mean_minus_std = mean - std
    diff_mean_plus_std = mean + std
    
    results.append({
        'Parameter': f"ideal_{param}",
        'Mean': mean,
        'Median': median,
        'Std': std,
        'Median-68%_lower': diff_median_68_lower,
        '68%_upper-Median': diff_median_68_upper,
        'Median-90%_lower': diff_median_90_lower,
        '90%_upper-Median': diff_median_90_upper,
        'Median-95%_lower': diff_median_95_lower,
        '95%_upper-Median': diff_median_95_upper,
        'Median-99%_lower': diff_median_99_lower,
        '99%_upper-Median': diff_median_99_upper,
        'Mean-Std': diff_mean_minus_std,
        'Mean+Std': diff_mean_plus_std
    })

results_df = pd.DataFrame(results)
results_df.to_csv('results/bs_final_ideal.csv', index=False)
results_df

,Parameter,Mean,Median,Std,Median-68%_lower,68%_upper-Median,Median-90%_lower,90%_upper-Median,Median-95%_lower,95%_upper-Median,Median-99%_lower,99%_upper-Median,Mean-Std,Mean+Std
0,ideal_N,356.544186,356.644946,0.689890,0.833655,0.480322,1.307278,1.056620,1.403533,1.237763,2.043424,1.460753,355.854295,357.234076
1,ideal_r,78.298110,78.319862,0.172232,0.193037,0.143345,0.318510,0.279595,0.363896,0.299478,0.455147,0.346268,78.125878,78.470343
2,ideal_sigma,0.149104,0.148585,0.009165,0.008966,0.010464,0.013098,0.016091,0.015955,0.017732,0.019865,0.021563,0.139939,0.158268
3,ideal_x0,80.461375,80.467003,0.077929,0.088712,0.060971,0.141692,0.124370,0.157127,0.151621,0.199076,0.159708,80.383446,80.539305
4,ideal_y0,136.603687,136.619978,0.165981,0.184445,0.137909,0.304026,0.291362,0.345851,0.299164,0.437388,0.332638,136.437706,136.769668
5,ideal_theta0,214.269646,214.276448,0.065436,0.074649,0.045760,0.115827,0.107417,0.133200,0.110543,0.189787,0.170027,214.204211,214.335082

In [3]:
# Load the radial/tangential CSV file
rt_df = pd.read_csv('results/bootstrap_results_radial_tangential.csv')

results = []
# Process radial/tangential data
for param in rt_df['Parameter']:
    row = rt_df[rt_df['Parameter'] == param].iloc[0]
    
    # Convert alpha values to degrees if they're alpha parameters
    if 'alpha' in param:
        mean = rad_to_deg(row['Mean'])
        median = rad_to_deg(row['Median'])
        std = rad_to_deg(row['Std'])
        ci_68_lower = rad_to_deg(row['68.0%_lower'])
        ci_68_upper = rad_to_deg(row['68.0%_upper'])
        ci_90_lower = rad_to_deg(row['90.0%_lower'])
        ci_90_upper = rad_to_deg(row['90.0%_upper'])
        ci_95_lower = rad_to_deg(row['95.0%_lower'])
        ci_95_upper = rad_to_deg(row['95.0%_upper'])
        ci_99_lower = rad_to_deg(row['99.0%_lower'])
        ci_99_upper = rad_to_deg(row['99.0%_upper'])
    else:
        mean = row['Mean']
        median = row['Median']
        std = row['Std']
        ci_68_lower = row['68.0%_lower']
        ci_68_upper = row['68.0%_upper']
        ci_90_lower = row['90.0%_lower']
        ci_90_upper = row['90.0%_upper']
        ci_95_lower = row['95.0%_lower']
        ci_95_upper = row['95.0%_upper']
        ci_99_lower = row['99.0%_lower']
        ci_99_upper = row['99.0%_upper']
    
    # Calculate differences
    diff_median_68_lower = median - ci_68_lower
    diff_median_68_upper = ci_68_upper - median
    diff_median_90_lower = median - ci_90_lower
    diff_median_90_upper = ci_90_upper - median
    diff_median_95_lower = median - ci_95_lower
    diff_median_95_upper = ci_95_upper - median
    diff_median_99_lower = median - ci_99_lower
    diff_median_99_upper = ci_99_upper - median
    diff_mean_minus_std = mean - std
    diff_mean_plus_std = mean + std
    
    results.append({
        'Parameter': f"rt_{param}",
        'Mean': mean,
        'Median': median,
        'Std': std,
        'Median-68%_lower': diff_median_68_lower,
        '68%_upper-Median': diff_median_68_upper,
        'Median-90%_lower': diff_median_90_lower,
        '90%_upper-Median': diff_median_90_upper,
        'Median-95%_lower': diff_median_95_lower,
        '95%_upper-Median': diff_median_95_upper,
        'Median-99%_lower': diff_median_99_lower,
        '99%_upper-Median': diff_median_99_upper,
        'Mean-Std': diff_mean_minus_std,
        'Mean+Std': diff_mean_plus_std
    })

results_df = pd.DataFrame(results)
results_df.to_csv('results/bs_final_radial_tangential.csv', index=False)
results_df

,Parameter,Mean,Median,Std,Median-68%_lower,68%_upper-Median,Median-90%_lower,90%_upper-Median,Median-95%_lower,95%_upper-Median,Median-99%_lower,99%_upper-Median,Mean-Std,Mean+Std
0,rt_N,357.277197,357.268049,0.034815,0.000724,0.003686,0.001599,0.056322,0.005077,0.123462,0.007764,0.201830,357.242382,357.312013
1,rt_r,77.846543,77.853888,0.029612,0.005220,0.003158,0.046388,0.004406,0.127885,0.005475,0.160051,0.006566,77.816931,77.876155
2,rt_sigma_r,0.025016,0.024975,0.002360,0.002204,0.002680,0.003692,0.004003,0.004198,0.004431,0.005502,0.004960,0.022656,0.027376
3,rt_sigma_t,0.116269,0.116586,0.007824,0.007113,0.007235,0.013841,0.010977,0.017863,0.012115,0.025279,0.015638,0.108444,0.124093
4,rt_x0_0,80.011572,80.017769,0.024281,0.003625,0.001095,0.036858,0.003261,0.106129,0.003572,0.131230,0.004608,79.987290,80.035853
5,rt_y0_0,136.314292,136.318498,0.016480,0.002460,0.000743,0.025016,0.002213,0.072032,0.002425,0.089068,0.003128,136.297812,136.330772
6,rt_alpha_0,214.165424,214.165523,0.000738,0.000774,0.000421,0.001367,0.001171,0.001766,0.001561,0.002142,0.001822,214.164686,214.166163
7,rt_x0_1,80.046311,80.057057,0.044023,0.038142,0.007596,0.097280,0.049787,0.143604,0.057650,0.180750,0.074360,80.002288,80.090334
8,rt_y0_1,136.399255,136.399412,0.030075,0.011780,0.016865,0.054500,0.051453,0.071324,0.065333,0.096823,0.082642,136.369180,136.429331
9,rt_alpha_1,214.345217,214.345478,0.040715,0.041230,0.033825,0.060296,0.065948,0.087644,0.071305,0.114593,0.090264,214.304501,214.385932
10,rt_x0_2,80.167679,80.185360,0.143019,0.008624,0.006923,0.043887,0.020793,0.459471,0.101220,0.816706,0.309375,80.024660,80.310698
11,rt_y0_2,136.154213,136.153553,0.063627,0.010798,0.013338,0.026714,0.023771,0.072582,0.156310,0.304284,0.249583,136.090586,136.217840
12,rt_alpha_2,214.470322,214.460153,0.116670,0.024033,0.019623,0.046849,0.051838,0.086709,0.374424,0.307932,0.628278,214.353652,214.586992
13,rt_x0_3,79.903860,79.901487,0.024628,0.023943,0.027981,0.040406,0.045452,0.045281,0.052244,0.048504,0.059731,79.879232,79.928489
14,rt_y0_3,136.223662,136.230986,0.030698,0.009844,0.006141,0.050444,0.011820,0.132806,0.012421,0.160719,0.013703,136.192964,136.254359
15,rt_alpha_3,214.750212,214.750248,0.023055,0.025537,0.025149,0.035382,0.035304,0.038689,0.041089,0.053210,0.051256,214.727157,214.773267
16,rt_x0_4,80.543926,80.542138,0.006997,0.000315,0.001111,0.000939,0.010626,0.001028,0.030585,0.001326,0.037818,80.536928,80.550923
17,rt_y0_4,136.312139,136.319420,0.028497,0.004526,0.001284,0.043276,0.003822,0.124558,0.004186,0.154022,0.005402,136.283641,136.340636
18,rt_alpha_4,214.266735,214.265157,0.007203,0.002006,0.002376,0.003272,0.011775,0.003756,0.024101,0.004345,0.040469,214.259532,214.273937
19,rt_x0_5,80.651956,80.647936,0.015854,0.001576,0.003865,0.002711,0.017590,0.003081,0.061079,0.003898,0.088236,80.636101,80.667810
20,rt_y0_5,136.413453,136.421054,0.027537,0.012059,0.004901,0.044463,0.008625,0.118742,0.009532,0.143114,0.012436,136.385917,136.440990
21,rt_alpha_5,214.204862,214.202241,0.039580,0.040549,0.040358,0.051177,0.084876,0.052849,0.086310,0.059313,0.086781,214.165282,214.244443
22,rt_x0_6,80.669934,80.667279,0.010036,0.001500,0.003132,0.002397,0.018530,0.002598,0.040543,0.002925,0.053545,80.659898,80.679970
23,rt_y0_6,136.097573,136.104726,0.027656,0.008626,0.004276,0.043991,0.006985,0.118926,0.007593,0.147988,0.008586,136.069916,136.125229
24,rt_alpha_6,214.627167,214.632166,0.043309,0.058641,0.056793,0.060259,0.059013,0.061009,0.059377,0.062182,0.084149,214.583858,214.670476
25,rt_x0_7,82.759688,82.751117,0.033558,0.002992,0.005282,0.004834,0.023552,0.005435,0.154903,0.006533,0.170617,82.726130,82.793246
26,rt_y0_7,136.790524,136.793468,0.021732,0.007355,0.009144,0.011540,0.013558,0.080839,0.014460,0.114082,0.015602,136.768792,136.812256
27,rt_alpha_7,212.860323,212.862776,0.038393,0.039044,0.038596,0.072660,0.054511,0.082078,0.062782,0.088683,0.085802,212.821930,212.898716